'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Game
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Game.Game", GetType(Game).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Character() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 曾經 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro1() As String
            Get
                Return ResourceManager.GetString("Intro1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 但是不必擔心 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro10() As String
            Get
                Return ResourceManager.GetString("Intro10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 第二位王儲已經上路了 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro11() As String
            Get
                Return ResourceManager.GetString("Intro11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 這是你長路的紀行 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro12() As String
            Get
                Return ResourceManager.GetString("Intro12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 這是你們的 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro13() As String
            Get
                Return ResourceManager.GetString("Intro13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 珍珠之歌 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro14() As String
            Get
                Return ResourceManager.GetString("Intro14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 天上有一個榮光的王國 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro2() As String
            Get
                Return ResourceManager.GetString("Intro2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 那國王派遣第一位王儲 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro3() As String
            Get
                Return ResourceManager.GetString("Intro3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 去黑暗之國尋找創世的珍珠 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro4() As String
            Get
                Return ResourceManager.GetString("Intro4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 於是 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro5() As String
            Get
                Return ResourceManager.GetString("Intro5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 第一位王儲走上了珍珠的追尋之路 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro6() As String
            Get
                Return ResourceManager.GetString("Intro6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 但他卻被欺騙 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro7() As String
            Get
                Return ResourceManager.GetString("Intro7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 忘記了自己的高貴 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro8() As String
            Get
                Return ResourceManager.GetString("Intro8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 以為自己是黑暗之國的王 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intro9() As String
            Get
                Return ResourceManager.GetString("Intro9", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
