'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Game
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MoscheBarton.Game", GetType(Game).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property _Continue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Continue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property AbilityL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AbilityL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property AbilityR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AbilityR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property AbyssClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AbyssClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property AbyssOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AbyssOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Boss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Boss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property BossLaser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BossLaser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property BossMusicCore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BossMusicCore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property BulletL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BulletL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property BulletR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BulletR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CLAN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLAN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CLAW0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLAW0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CLAW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLAW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CLAW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLAW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CLNN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLNN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CLNW0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLNW0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CLNW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLNW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CLNW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLNW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Cobblestone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cobblestone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property ContinueA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContinueA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CRAN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRAN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CRAW0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRAW0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CRAW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRAW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CRAW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRAW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CRNN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRNN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CRNW0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRNW0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CRNW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRNW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CRNW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRNW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Day() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Day", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Fence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Log() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Log", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property NextLevel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NextLevel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PauseButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PauseButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PauseButtonA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PauseButtonA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Planks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Planks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SlimeL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SlimeL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SlimeR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SlimeR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Sunset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sunset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property ToMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ToMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property ToMenuA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ToMenuA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property XPBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XPBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
